version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=replace_me
      - ADMIN_USER=itinventory
      - ADMIN_PASS=chl!@2025
